server:
  port: 8080

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  application:
    name: simple_board


  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpleboard_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 0710@@

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mybatis-config.xml